---
title: "FTLE_analysis"
author: "Elise Nicolas"
date: "2026-08-03"
output: html_document
---

# Libraries, paths and global variables

```{r}
# libraries
library(ncdf4)
library(ggplot2)
library(maps)
# Paths
folder_path <- "/run/media/elise/KER22/données elise/raw/FTLE"

# Global variables
year <- 2023
```

# Import variables

```{r}
# Get dates from year 
Sv_path <- paste0("/run/media/elise/KER22/données elise/raw/acoustic/Acoustique_obsaus_", year, "_-100_-50dB_50ESU_10m.nc")
ds_Sv <- nc_open(Sv_path)

lat_sv <- ncvar_get(ds_Sv, "latitude")
lon_sv <- ncvar_get(ds_Sv, "longitude")
print(c(min(lat_sv), max(lat_sv), min(lon_sv), max(lon_sv)))
time <- ncvar_get(ds_Sv, "time")

time_bis <- as.POSIXct(
  time * 86400,
  origin = "1950-01-01",
  tz = "UTC"
) # nécessaire pour extraire date unique for some reason as.Date ne fonctionnait pas
dates <- as.Date(time_bis)

dates_unique <- unique(dates)
nc_close(ds_Sv)
rm(ds_Sv, time, Sv_path)

# create string matching pigmean filenames "YYYYMMDD"
dates_unique_str <- format(dates_unique, "%Y-%m-%d")
dates_all_str <-  format(dates, "%Y-%m-%d") # pour tous les jours de l'année donnée
print(dates_unique_str)

# Get FTLE datas to corresponding dates
files <- list.files(
  path = folder_path,
  pattern = paste0("map_(", paste(dates_unique_str, collapse = "|"), ").*\\.nc$"),
  full.names = TRUE
)
# verif all dates found
n_dates_found <- length(files)
n_dates <- length(dates_unique)
print(c(n_dates, n_dates_found)) # 2021 OK, 2022 OK, 2023 1 missing (2023-02-26)
```

# Colocaliser sv et ftle

```{r}
ftle <- data.frame(
  time = time_bis,
  lat_sv = lat_sv,
  lon_sv = lon_sv,
  lat_ftle = NA_real_,
  lon_ftle = NA_real_, 
  ftle = NA_real_
)

length(dates_unique)

for(date_i in dates_unique_str){

    # indice ESU à cette date
    ind <- which(dates_all_str == date_i)

    # ouvrir le fichier du jour i
    pattern <- paste0("map_", date_i, ".*\\.nc$")
    filename <- list.files(
      folder_path,
      pattern = pattern,
      full.names = TRUE
    )
    print(filename)
    if(length(filename)==0)
        next

    ds <- nc_open(filename[1])
    
    # récupérer les coordonnées PIGMeANN du jour
    lat_ftle <- ds$dim$lat$vals
    lon_ftle <- ds$dim$lon$vals
    print(c(min(lat_ftle), max(lat_ftle), min(lon_ftle), max(lon_ftle)))
    # trouver les pixels PIGMeANN les plus proches des stations
    idx_lon <- sapply(
      lon_sv[ind],
      function(x) which.min(abs(lon_ftle - x))
    )

    idx_lat <- sapply(
      lat_sv[ind],
      function(x) which.min(abs(lat_ftle - x))
    )

    # enregistrer les coordonnées ftle associées
    ftle$lat_ftle[ind] <- lat_ftle[idx_lat]
    ftle$lon_ftle[ind] <- lon_ftle[idx_lon]

    ftle_data <- ncvar_get(ds, "FTLE")
   
    # extraction au voisinage du point
    for(j in seq_along(ind)){

        i <- ind[j]

        ilon <- idx_lon[j]
        ilat <- idx_lat[j]


        lon_win <- max(1, ilon-1):min(nrow(ftle_data), ilon+1)
        lat_win <- max(1, ilat-1):min(ncol(ftle_data), ilat+1)


        ftle$ftle[i] <- mean(ftle_data[lon_win, lat_win], na.rm = TRUE)
    }
  

    nc_close(ds)
}

saveRDS(ftle, paste0("/run/media/elise/KER22/données elise/elisou_ta_stagiaire_pref/prepross/FTLE/ftle", year, ".rds"))

# verifications

rds_ds <- readRDS(paste0("/run/media/elise/KER22/données elise/elisou_ta_stagiaire_pref/prepross/FTLE/ftle", year, ".rds"))
print(rds_ds)
rds_ds<- rds_ds[rds_ds$lat_sv < -30, ]
rds_ds<- rds_ds[rds_ds$lon_sv > 40, ]
dlon <- rds_ds$lon_ftle - rds_ds$lon_sv
dlat <- rds_ds$lat_ftle - rds_ds$lat_sv

summary(dlon)
summary(dlat)
```

# Explore nc

```{r}
ds_ftle <- nc_open(files[1])
print(ds_ftle)
ftle <- ncvar_get(ds_ftle, "FTLE")
print(ds_ftle$var$FTLE$dim)
lat <- ds_ftle$dim$lat$vals
lon <- ds_ftle$dim$lon$vals

# map
image(lon, lat, ftle)
```
