---
title: "FOD (fpca bivariée + clustering GMM)"
author: "Elise Nicolas"
date: "2026-07-22"
output: html_document
---
## librairies
```{r}
# librairies
library(ncdf4)
library(rpart)
library(rpart.plot)
library(splines)
library(fda)
library(zoo)
library(pbapply)
library(glue)
library(mclust)
library(fields)
```

## Ouverture des datasets

```{r}
rm(list = ls())
path = "/run/media/mmolinet/DATA1/data/raw/temperature_salinite/cmems_mod_glo_phy_my_0.083deg_P1D-m_thetao-so_40.00E-95.00E_60.00S-20.00S_0.49-5727.92m_2021-01-09-2021-03-03.nc"
ds <- nc_open(path)
thetao <- ncvar_get(ds, "thetao") # (lon, lat, depth, time)
so <- ncvar_get(ds, "so") # (lon, lat, depth, time)
depth <- ncvar_get(ds, "depth")
lat <- ncvar_get(ds, "latitude")
lon <- ncvar_get(ds, "longitude")

# libérer esoace mémoire
rm(ds)
gc()

# small ds
# thetao = thetao[,,,1:4]
# so = so[,,,1:4]
```

## Cropper les données à 500m (et a 40eS)

```{r}
i_500m <- which.min(abs(depth - 500))
depth <- depth[1:i_500m]
# i_lat40 <- which.min(abs(lat+40))
# lat <- lat[1:i_lat40]

thetao <- thetao[, , 1:i_500m,] # 1:i_lat40
so <- so[, , 1:i_500m,] # 1:i_lat40

gc()
```

## Applatir et retirer les nans

```{r}
# -------------- applatir les mats de temp et sal
dim_ds <- dim(thetao)

nlon   <- dim_ds[1]
nlat   <- dim_ds[2]
ndepth   <- dim_ds[3]
ntime   <- dim_ds[4]

thetao_flat <- matrix(aperm(thetao, c(1,2,4,3)), ncol = ndepth)
so_flat <- matrix(aperm(so, c(1,2,4,3)), ncol = ndepth)
dim(thetao_flat)

# vérifier impact de retirer tous les profils nans
sum(rowSums(is.na(thetao_flat)) > 0)/nrow(thetao_flat) #0.02
sum(rowSums(is.na(so_flat)) > 0)/nrow(so_flat) #0.02

# mask
mask_common <- !apply(is.na(thetao_flat), 1, any) &
               !apply(is.na(so_flat), 1, any)
sum(!mask_common)/length(mask_common)

# apply mask
thetao_flat_clean <-thetao_flat[mask_common,]
so_flat_clean <- so_flat[mask_common,]
sum(is.na(so_flat_clean))

plot(thetao_flat_clean[10000, ], -depth, type = 'l')



nrow(thetao_flat)
length(mask_common)

# rm(thetao_flat, so_flat)
gc()
rm(so, thetao)
```

```{r} 
# gestion des nans interp linéaire
# # --------------- gestion des nans thetao
# # 1. retirer les profils qui ont + de 20% de nans
# 
# NA_count <- rowSums(is.na(thetao_500_flat))
# ratio_NA <- NA_count / nrow(thetao_500_flat)
# mask <- NA_count < 50
# unique(NA_count) # 1 à 6 nans par profils
# thetao_500_flat <- thetao_500_flat[mask, ]
# which(rowSums(is.na(thetao_500_flat)) == ncol(thetao_500_flat)) # aucun profil entierement nan
# rm (NA_count, ration_NA,  mask)
# gc()
# 
# 
# # 2. interpolation des nans restants
# thetao_500_flat2 <- matrix(
#   NA_real_,
#   nrow = nrow(thetao_500_flat),
#   ncol = ncol(thetao_500_flat)
# )
# for (i in seq_len(nrow(thetao_500_flat))) {
#   thetao_500_flat2[i, ] <- approx(
#     depth_500m[!is.na(thetao_500_flat[i, ])],
#     thetao_500_flat[i, !is.na(thetao_500_flat[i, ])],
#     xout = depth_500m,
#     rule = 2 # prolonger les valeurs aux extremités
#   )$y
# }
# which(rowSums(is.na(thetao_500_flat2)) > 0)
# 
# gc()
# class(thetao_500_flat2)
# dim(thetao_500_flat2)
# anyNA(thetao_500_flat2)
# 
# # 3. verification des nans résiduels
# anyNA(thetao_500_flat)
# gc()
# save(thetao_500_flat2, file = "thetao_500_flat2.RData")
# 
# 
# # --------------- gestion des nans so
# # 1. retirer les profils qui ont + de 20% de nans
# 
# NA_count <- rowSums(is.na(so_500_flat))
# ratio_NA <- NA_count / ncol(so_500_flat)
# mask <- ratio_NA < 0.2
# so_500_flat <- so_500_flat[mask, ]
# rm (NA_count, ration_NA,  mask)
# gc()
# 
# # 2. interpolation des nans restants
# so_500_flat2 <- matrix(
#   NA_real_,
#   nrow = nrow(so_500_flat),
#   ncol = ncol(so_500_flat)
# )
# for (i in seq_len(nrow(so_500_flat))) {
#   so_500_flat2[i, ] <- approx(
#     depth_500m[!is.na(so_500_flat[i, ])],
#     so_500_flat[i, !is.na(so_500_flat[i, ])],
#     xout = depth_500m,
#     rule = 2 # prolonger les valeurs aux extremités
#   )$y
# }
# which(rowSums(is.na(so_500_flat2)) > 0)
# gc()
# 
# # 3. verification des nans résiduels
# anyNA(so_500_flat)
# gc()
# save(so_500_flat2, file = "thetao_500_flat.RData")
```


## Estimation fonctionelle
```{r}
# -------------- projection sur base de B-spline
# hyperparams
K <- 25 # nombre de fonction de base
r <- 4 # ordre de la fonction de base
lambda <- 0.25 # poids de la pénalisation

length(depth)
# base de Bsplines
phi <- bs(
    depth,
    df = K,
    degree = r-1,
    intercept = TRUE
)

phi <- as.matrix(phi)

# penalisation
D2 <- diff(diag(K), differences = 2)
R <- t(D2) %*% D2

# résolution 
A <- crossprod(phi) + lambda * R
dim(A)
qr(A)$rank
B <- solve(A, t(phi))

coef_thetao <- thetao_flat_clean %*% t(B)
coef_so <- so_flat_clean %*% t(B)

gc()

save(
  coef_thetao,
  coef_so,
  phi,
  B,
  depth,
  K,
  r,
  lambda,
  file = sprintf(
    "coefs_bivariate_bspline_K%d_r%d_lambda%f.RData",
    K, r, lambda
  )
)
gc()
```

## Check profils Bspline
```{r}
# so_rec <- coef_so %*% t(phi)
thetao_rec <- coef_thetao %*% t(phi)
i <- 170  # numéro du profil à regarder

plot(
  thetao_flat_clean[i, ], 
  depth,
  type = "l",
  ylim = rev(range(depth)),
  xlab = "temp",
  ylab = "Profondeur (m)"
)

lines(
  thetao_rec[i, ],
  depth,
  col = "red",
  lwd = 2
)

legend(
  "bottomright",
  legend = c("Original", "B-spline"),
  col = c("black", "red"),
  lty = 1,
  lwd = c(1, 2)
)
```

## Affichage de la projection 
```{r}
load("~/Elisou/MIO_part_III/fod/coefs_bivariate_bspline_K25_r4_lambda0.250000.RData")
rm(A, B, D2, phi, R)
# concatener
coef_biv <- cbind(
  coef_thetao,
  coef_so
)
dim(coef_biv)
rm(coef_so, coef_thetao)
# centrage
alpha_mean <- colMeans(coef_biv)

Xc <- scale(
  coef_biv,
  center = alpha_mean,
  scale = FALSE
)

# covariance des coefficients
V <- crossprod(Xc) / (nrow(Xc)-1)

# décomposition spectrale
eig <- eigen(V, symmetric = TRUE)

# tri décroissant
ord <- order(eig$values, decreasing = TRUE)

lambda <- eig$values[ord]
U <- eig$vectors[, ord]

# garder les n premières composantes
nharm <- 10

U <- U[,1:nharm]
lambda <- lambda[1:nharm]

# scores FPCA
scores <- Xc %*% U 
dim(scores) # (n, n_harm)

# afficher pc1 vs pc2
# plot(
#   scores[,1],
#   scores[,2],
#   xlab="PC1",
#   ylab="PC2",
#   pch=19,
#   cex = 0.05
# )
```

## GMM clustering
```{r}
gmm <- Mclust( #objet modele
  scores,
  G=4:6,
  model = "VVV"
)
saveRDS(gmm,file = "mclust_results.rds")
save(mask_common, file = "mask_common.RData")

summary(gmm) # resultat
nclust <- gmm$G # nb de cluster choisit par bic

# creer softclasses
seuil <- 0.8 # seuil soft class
max_prob <- apply(gmm$z, 1, max)# probabilité max pour chaque profil
cluster <- gmm$classification # classe la plus probable

# création d'une classe "incertaine"
cluster_soft <- cluster
cluster_soft[max_prob < seuil] <- 0

# flatten cluster
cluster_flat <- rep(NA_integer_, length(mask_common))
cluster_flat[mask_common] <- cluster_soft

# remettre dans bonnes dimensions (spatiales et temporelles)
nlon <- length(lon)
nlat <- length(lat)
cluster_map <- array(
  cluster_flat,
  dim = c(nlon, nlat, ntime)
)

# plot
cols <- c( # colormap
  "grey80",
  rainbow(nclust)
)

i = 2
image.plot(
  x = lon,
  y = lat,
  z = cluster_map[,,i],
  col = cols,
  breaks = seq(-0.5, nclust + 0.5, 1),
  legend.only = FALSE,
  axis.args = list(
    at = 0:nclust,
    labels = c("Transition", paste( 1:nclust))
  )
)
```

